### ISSUE TITLE
[Bug]: Self hosted server blank screen

### ISSUE THREAD

**Issue by GudBoiNero** [Miruro-no-kuon/Miruro#251]
### What went wrong?

The page loads in but doesnt display anything

### How'd you stumble upon it?

![image](https://github.com/user-attachments/assets/771ffe4e-837e-465f-959e-d7d848609803)

im not sure if its necessary to change from `public-miruro-consumet-api.vercel.app`. but whenever i open my app it goes completely black (loads the favicon and html and everything) and throws a weird error-

```
Uncaught TypeError: Cannot read properties of undefined (reading 'endsWith')
    at fR (index-BUbPffLA.js:2528:4757)
    at index-BUbPffLA.js:2528:4790Understand this errorAI
manifest.json:1 Manifest: unknown 'orientation' value ignored.Understand this warningAI
```

### What you hoped for vs. What actually happened

The page should've loaded and showed the main menu.

### Anything else we should know?

I'm running this in docker, and i'm not sure how to properly set up the environment file. Like for example, am I supposed to change the `VITE_BACKEND_URL`, if so, what am I supposed to set it to? It's not clear where I'm supposed to get a link from.

### Which version was acting up?

0.5.2

### Which browsers were a bummer?

Chrome

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct.

**Comment by GudBoiNero** [comment]
For more information, this is my Dockerfile

```Dockerfile
# Use a base image with Node.js
FROM node:18

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash

# Add Bun to PATH
ENV BUN_INSTALL="/root/.bun"
ENV PATH="${BUN_INSTALL}/bin:${PATH}"

# Set the working directory
WORKDIR /app

# Copy the .env file
COPY .env .env

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the project with Vite
RUN npm run build

# Expose the port that the app listens on (default is 3000)
EXPOSE 3000

# Start the app using Bun
CMD ["bun", "run", "./server/server.ts"]

```

**Comment by GudBoiNero** [comment]
I have to host my own Consumet instance. Oops.
